# Generated by Django 6.0.6 on 2026-06-30 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DDS', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionCategories',
            new_name='TransactionCategoriesModel',
        ),
        migrations.RenameModel(
            old_name='Transaction',
            new_name='TransactionModel',
        ),
        migrations.RenameModel(
            old_name='TransactionStatus',
            new_name='TransactionStatusModel',
        ),
        migrations.RenameModel(
            old_name='TransactionSubCategories',
            new_name='TransactionSubCategoriesModel',
        ),
        migrations.RenameModel(
            old_name='TransactionType',
            new_name='TransactionTypeModel',
        ),
        migrations.AlterModelTable(
            name='transactioncategoriesmodel',
            table='transaction_categories',
        ),
        migrations.AlterModelTable(
            name='transactionmodel',
            table='transactions',
        ),
        migrations.AlterModelTable(
            name='transactionstatusmodel',
            table='transaction_statuses',
        ),
        migrations.AlterModelTable(
            name='transactionsubcategoriesmodel',
            table='transaction_sub_categories',
        ),
        migrations.AlterModelTable(
            name='transactiontypemodel',
            table='transaction_types',
        ),
    ]
